# Generated by Django 4.0.3 on 2022-03-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='stock_amount',
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(editable=False, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stock')),
            ],
        ),
    ]
