# Generated by Django 4.0.3 on 2022-03-11 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_investor_stock_amount_alter_stock_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockorder',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.investor'),
        ),
        migrations.AlterField(
            model_name='stockorder',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='stock',
            table=None,
        ),
    ]
