# Generated by Django 4.0.3 on 2022-03-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_stockorder_user_alter_stockorder_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockorder',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
