# Generated by Django 4.0.3 on 2022-03-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_stockorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='stock_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
