# Generated by Django 4.0.3 on 2022-03-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_investor_stock_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='stock_amount',
            new_name='total_stock_amount',
        ),
    ]
