# Generated by Django 4.0.3 on 2022-03-11 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_remove_stockorder_investor_stockorder_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockorder',
            name='user',
        ),
        migrations.AddField(
            model_name='stockorder',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
