# Generated by Django 4.0.3 on 2022-03-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_user_investor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='name',
            new_name='username',
        ),
    ]
