# Generated by Django 4.0.3 on 2022-03-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_name_investor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockorder',
            name='total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
