# Generated by Django 4.0.3 on 2022-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_stockorder_total_investor_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='total_stock_amount',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
