# Generated by Django 4.0.3 on 2022-03-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_investor_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='balance',
            field=models.PositiveIntegerField(default=10000, editable=False),
        ),
    ]
