# Generated by Django 4.0.3 on 2022-03-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockId', models.IntegerField()),
                ('stockName', models.CharField(max_length=32)),
                ('stockAbv', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userName',
        ),
    ]
