# Generated by Django 4.0.3 on 2022-03-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_stocks_rename_userid_user_userid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stocks',
            new_name='stock',
        ),
    ]
