# Generated by Django 4.0.3 on 2022-03-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_stocks_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stockPrice',
            field=models.IntegerField(default=0),
        ),
    ]
