# Generated by Django 4.0.3 on 2022-03-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_stock_stockabv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stockAbv',
            new_name='abv',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stockName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stockPrice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stockId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
